"use client";

import { api } from "@/trpc/react";

export default function StatsSection() {
  const [settings] = api.settings.site.useSuspenseQuery();

  return (
    <section className="py-12 md:py-20">
      <div className="mx-auto max-w-5xl space-y-8 px-6 md:space-y-16">
        <div className="relative z-10 mx-auto max-w-xl space-y-6 text-center">
          <h2 className="text-4xl font-medium lg:text-5xl">
            {settings?.name} in numbers
          </h2>
          <p>
            {settings?.name} supports Facebook, Twitter, and LinkedIn. More are
            on the way. These numbers are growing every day generated by
            individuals and businesses around the world.
          </p>
        </div>

        <div className="grid gap-12 divide-y *:text-center md:grid-cols-3 md:gap-2 md:divide-x md:divide-y-0">
          <div className="space-y-4">
            <div className="text-5xl font-bold">+1200</div>
            <p>Tweet on Twitter</p>
          </div>
          <div className="space-y-4">
            <div className="text-5xl font-bold">22 Million</div>
            <p>Active Users</p>
          </div>
          <div className="space-y-4">
            <div className="text-5xl font-bold">+500</div>
            <p>Posts on Facebook</p>
          </div>
        </div>
      </div>
    </section>
  );
}
